#!/usr/bin/ruby

require 'oga'
require 'json'
require 'open-uri'
require 'thread'
require 'open3'
require 'os'

def fetch_sound_list(url)
	puts 'fetching sound list...'
	albumid = ""

	match = /^https:\/\/www\.ximalaya\.com\/[^\/]+\/(\d+)/.match(url)
	if match
		albumid = match[1]
	else
		puts "url format is not correct"
		exit 1
	end

	body = open(url).read
	document = Oga.parse_html(body)
	h2s = document.xpath('//div[contains(@class, "head")]/h2')
	if h2s.length == 0
		puts "can not fetch h2 contains album count"
		exit 1
	end

	album_count = nil
	h2s.each do |h2|
		match = /\((\d+)\)/.match(h2.text)
		if match
			album_count = match[1]
			break
		end
	end

	if not album_count
		puts "cannot fetch album count"
		exit 1
	end

	body = open('https://www.ximalaya.com/revision/play/album?albumId=' + albumid + '&pageSize=' + album_count).read
	response = JSON.parse(body)
	if response['ret'] != 200
		puts "fetch album list failed"
		exit 1
	end

	return Hash[response['data']['tracksAudioPlay'].map{ |elem| [elem['trackName'].match(/^\d/) ? elem['trackName'] : sprintf("%02d%s", elem['index'], elem['trackName']), elem['src']] }.map{ |elem| [elem[0].gsub(/[\s\(\)\"\'\\\/-]/, '').gsub(/\.mp3$/, ''), elem[1]] }]
end

def fetch_audio_url(id, name)
	return if File.exist?(name + '.mp3') or File.exist?(name + '.m4a')
	puts 'fetching audio url for ' + name + '...'
	body = open('http://www.ximalaya.com/tracks/' + id + '.json').read
	return JSON.parse(body)['play_path_32']
end

def convert_m4a_to_mp3(name)
	if not File.exist?(name + '.mp3') and File.exist?(name + '.m4a')
		puts 'converting ' + name + '...'
		stdout, stderr, status = Open3.capture3('ffmpeg -loglevel 16 -i "' + name + '.m4a" -map 0:a -codec:a libmp3lame -q:a 4 -map_metadata -1 "' + name + '.mp3"')
		if status.success?
			puts 'convert ' + name + ' successfully'
		else
			puts 'convert ' + name + ' failed '
			File.delete(name + '.mp3') if File.exist?(name + '.mp3')
		end
	end
end

def fetch_audio_file(url, name)
	return if File.exist?(name + '.m4a') or File.exist?(name + '.mp3') or url == nil
	puts 'downloading ' + name + '...'
	open(name + '.m4a', 'wb') do |file|
		file << open(url).read
	end
	puts 'download ' + name + ' successfully'
end

def fetch_audio(argv)
	if argv.empty?
		puts "usage: ./ximalaya url [filter]"
		exit 1
	end

	url = argv[0]
	filter = argv[1]

	queue = Queue.new
	hash = fetch_sound_list(url)
	hash = hash.select{ |key, value| value.force_encoding('UTF-8').match(/#{filter}/) } if filter
	thread_count = [[OS.cpu_count - 1, 1].max, hash.keys.length].min
	puts 'create ' + thread_count.to_s + ' threads'
	thread_pool = (0...thread_count).map do
		Thread.new do
			begin
				while name = queue.pop
					convert_m4a_to_mp3(name)
				end
			end
		end
	end
	begin
		hash.keys.each do |name|
			url = hash[name]
			fetch_audio_file(url, name)
			queue.push name
		end
	rescue Exception => e
		puts "catch one Exception: " + e.message
		puts e.backtrace
	end
	(0...thread_count).map do ||
		queue.push nil
	end
	thread_pool.map(&:join)
	hash.keys.each { |name| File.delete(name + '.m4a') if File.exist?(name + '.m4a') }
end

fetch_audio(ARGV)
